Flesh out expected test failure action

diff --git a/.github/workflows/_internal_expected_test_failure.yml b/.github/workflows/_internal_expected_test_failure.yml
--- a/.github/workflows/_internal_expected_test_failure.yml
+++ b/.github/workflows/_internal_expected_test_failure.yml
@@ -24,3 +24,19 @@ jobs:
       manifest_dir: ${{inputs.manifest_dir}}
       rust_toolchain: ${{inputs.rust_toolchain}}
       cargo_test_args: ${{inputs.cargo_test_args}}
+
+  expect_test_failure:
+    runs-on: ubuntu-latest
+    needs: lints
+    steps:
+      - name: transform expected failure
+        id: expected_failure
+        env:
+          NEEDS_JSON: ${{toJSON(needs)}}
+          JQ_FAIL_PROGRAM: >
+            .lints.outputs["_internal_tests_result"] == "failure"
+        run: >
+          echo "did_fail=$(echo "$NEEDS_JSON" | jq -r "$JQ_FAIL_PROGRAM")" | tee -a $GITHUB_OUTPUT
+      - name: expect failure
+        run: exit 1
+        if: steps.expected_failure.outputs.did_fail != 'true'
