Rewrite the test workflow as an action

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -14,11 +14,13 @@ jobs:
       fail-fast: false
       matrix:
         rust_toolchain: ["stable", "nightly"]
-    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
-    secrets: inherit
-    with:
-      manifest_dir: "tests/success"
-      rust_toolchain: ${{ matrix.rust_toolchain }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/test
+        with:
+          manifest_dir: "tests/success"
+          rust_toolchain: ${{ matrix.rust_toolchain }}
 
   success_lints:
     strategy:
@@ -32,11 +34,13 @@ jobs:
       rust_toolchain: ${{ matrix.rust_toolchain }}
 
   success_tests_c_dep:
-    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
-    secrets: inherit
-    with:
-      manifest_dir: "tests/success-with-c-dependency"
-      apt_install_packages: libzfslinux-dev
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/test
+        with:
+          manifest_dir: "tests/success-with-c-dependency"
+          apt_install_packages: libzfslinux-dev
 
   success_lints_c_dep:
     uses: "./.github/workflows/ci_baseline_rust_lints.yml"
@@ -46,26 +50,46 @@ jobs:
       apt_install_packages: libzfslinux-dev
 
   # Test jobs that expect failure:
-  lint_failure_clippy:
+  failure_lint_clippy:
     uses: "./.github/workflows/_internal_expected_lint_failure.yml"
     with:
       expected_failure: clippy
       manifest_dir: "tests/clippy-failure"
 
-  lint_failure_fmt:
+  failure_lint_fmt:
     uses: "./.github/workflows/_internal_expected_lint_failure.yml"
     with:
       expected_failure: fmt
       manifest_dir: "tests/fmt-failure"
 
-  test_failure_nightly:
-    uses: "./.github/workflows/_internal_expected_test_failure.yml"
-    with:
-      manifest_dir: tests/failure
-      rust_toolchain: nightly
+  failure_test_nightly:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/test
+        with:
+          manifest_dir: tests/failure
+          rust_toolchain: nightly
+        id: failure
+        continue-on-error: true
+      - name: Expect failure
+        run: |
+          echo "::setFailed::Expected the failure step to fail; instead: ${{steps.failure.outcome}}"
+          exit 1
+        if: ${{ success() && steps.failure.outcome != 'failure' }}
 
-  test_failure_stable:
-    uses: "./.github/workflows/_internal_expected_test_failure.yml"
-    with:
-      manifest_dir: tests/failure
-      rust_toolchain: stable
+  failure_test_stable:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/test
+        with:
+          manifest_dir: tests/failure
+          rust_toolchain: stable
+        id: failure
+        continue-on-error: true
+      - name: Expect failure
+        run: |
+          echo "::setFailed::Expected the failure step to fail; instead: ${{steps.failure.outcome}}"
+          exit 1
+        if: ${{ success() && steps.failure.outcome != 'failure' }}
