Move out the clippy action from the lint workflow

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -35,6 +35,19 @@ jobs:
           manifest_dir: "tests/success"
           rust_toolchain: ${{ matrix.rust_toolchain }}
 
+  success_clippy:
+    strategy:
+      fail-fast: false
+      matrix:
+        rust_toolchain: ["stable", "nightly"]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/clippy
+        with:
+          manifest_dir: "tests/success"
+          rust_toolchain: ${{ matrix.rust_toolchain }}
+
   success_lints:
     strategy:
       fail-fast: false
@@ -64,10 +77,19 @@ jobs:
 
   # Test jobs that expect failure:
   failure_lint_clippy:
-    uses: "./.github/workflows/_internal_expected_lint_failure.yml"
-    with:
-      expected_failure: clippy
-      manifest_dir: "tests/clippy-failure"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./actions/clippy
+        with:
+          manifest_dir: "tests/clippy-failure"
+        id: failure
+        continue-on-error: true
+      - name: Expect failure
+        run: |
+          echo "::setFailed::Expected the failure step to fail; instead: ${{steps.failure.outcome}}"
+          exit 1
+        if: ${{ success() && steps.failure.outcome != 'failure' }}
 
   failure_fmt:
     runs-on: ubuntu-latest
@@ -75,7 +97,6 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./actions/fmt
         with:
-          expected_failure: fmt
           manifest_dir: "tests/fmt-failure"
         id: failure
         continue-on-error: true
